# cloudbuild.yaml
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$REPO_NAME'
      - '--image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--port=$PORT'
      - '--allow-unauthenticated'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
  
# Set a timeout for the build
timeout: '1200s'

# Define substitution variables
substitutions:
  _PORT: '8080'  # Default port, will use $PORT from container if available

# Logging configuration
options:
  logging: CLOUD_LOGGING_ONLY
